services:
  - type: web
    name: ig-chat-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false # Set securely in Dashboard
      - key: REDIS_URL
        sync: false # Set securely in Dashboard
